spring.application.name=heythere-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_analysis?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.port=8090
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Gemini API Configuration
#gemini.api.key=AIzaSyAltY__qRFX8aLMbzO9wEHga6z-Q1txCeA
#gemini.api.key=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
#openrouter.api.key=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
openrouter.api.key=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
